// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformDemo.Data;

#nullable disable

namespace PlatformDemo.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformDemo.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test Customer 1",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test Customer 2",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Test Customer 3",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Test Customer 4",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Test Customer 5",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Test Customer 6",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Test Customer 7",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Test Customer 8",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Test Customer 9",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Test Customer 10",
                            PhoneNumber = "+63123445784"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Test Customer 11",
                            PhoneNumber = "+63123445784"
                        });
                });

            modelBuilder.Entity("PlatformDemo.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 617m,
                            CustomerId = 1,
                            OrderNumber = "ORDNUM-1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 163m,
                            CustomerId = 2,
                            OrderNumber = "ORDNUM-2"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 494m,
                            CustomerId = 2,
                            OrderNumber = "ORDNUM-3"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 113m,
                            CustomerId = 3,
                            OrderNumber = "ORDNUM-4"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 337m,
                            CustomerId = 3,
                            OrderNumber = "ORDNUM-5"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 993m,
                            CustomerId = 3,
                            OrderNumber = "ORDNUM-6"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 51m,
                            CustomerId = 3,
                            OrderNumber = "ORDNUM-7"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 52m,
                            CustomerId = 4,
                            OrderNumber = "ORDNUM-8"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 266m,
                            CustomerId = 5,
                            OrderNumber = "ORDNUM-9"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 463m,
                            CustomerId = 7,
                            OrderNumber = "ORDNUM-10"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 522m,
                            CustomerId = 7,
                            OrderNumber = "ORDNUM-11"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 550m,
                            CustomerId = 8,
                            OrderNumber = "ORDNUM-12"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 804m,
                            CustomerId = 9,
                            OrderNumber = "ORDNUM-13"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 692m,
                            CustomerId = 9,
                            OrderNumber = "ORDNUM-14"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 693m,
                            CustomerId = 9,
                            OrderNumber = "ORDNUM-15"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 893m,
                            CustomerId = 9,
                            OrderNumber = "ORDNUM-16"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 222m,
                            CustomerId = 9,
                            OrderNumber = "ORDNUM-17"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 814m,
                            CustomerId = 10,
                            OrderNumber = "ORDNUM-18"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 13m,
                            CustomerId = 10,
                            OrderNumber = "ORDNUM-19"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 324m,
                            CustomerId = 11,
                            OrderNumber = "ORDNUM-20"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 402m,
                            CustomerId = 11,
                            OrderNumber = "ORDNUM-21"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 463m,
                            CustomerId = 11,
                            OrderNumber = "ORDNUM-22"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 24m,
                            CustomerId = 11,
                            OrderNumber = "ORDNUM-23"
                        });
                });

            modelBuilder.Entity("PlatformDemo.Data.Models.Order", b =>
                {
                    b.HasOne("PlatformDemo.Data.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PlatformDemo.Data.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
